version: v1
name: modern-docker-secret
type: secret
secret:
  type: cloud-kernel-image-pull
  acl: r
  data:
    .dockerconfigjson: |
      {
        "auths": {
          "https://index.docker.io/v1/": {
            "auth": "",                  
            "username": "rubiklabs",
            "password": ""
          }
        }
      } 