name: gitsecret
version: v1
type: instance-secret
tags:
  - dataos:type:resource
  - dataos:type:cluster-resource
  - dataos:resource:instance-secret
  - dataos:layer:user
description: ${entity_title} secrets for lens repos
layer: user
instance-secret:
  type: key-value
  acl: rw
  data:
    GITSYNC_USERNAME: {{ GITSYNC_USERNAME }}
    GITSYNC_PASSWORD: {{ GITSYNC_PASSWORD }}