name: llm-instance-secret
version: v1
type: secret
tags:
  - dataos:type:resource
  - dataos:resource:secret
  - dataos:layer:user
  - dataos:workspace:public
description: LLM Isntance Secert Python Script Secrets
workspace: public
secret:
  type: key-value
  acl: r
  data:
    OPENAI_API_KEY: 