name: wf-${entity}-quality
version: v1
type: workflow
tags:
  - Tier.Gold
description: |
  Performs quality checks on raw ${entity} event data to ensure completeness, consistency, and schema compliance—strengthening data trust and enabling better business decisions.
workspace: public
workflow:
  # schedule:
  #   cron: '*/5 * * * *'
  #   concurrencyPolicy: Forbid
  dag:
    - name: ${entity}-quality
      description: |
        Performs quality checks on raw ${entity} event data to ensure completeness, consistency, and schema compliance—strengthening data trust and enabling better business decisions.
      title: ${entity_title} Quality Assertion
      spec:
        stack: soda+python:1.0 
        logLevel: INFO
        compute: runnable-default
        resources:
          requests:
            cpu: 1000m
            memory: 250Mi
          limits:
            cpu: 1000m
            memory: 250Mi
        stackSpec:
          inputs:
            - dataset: dataos://icebase:${entity}/${entity}?acl=rw 
              options:
                engine: minerva
                clusterName: system   
              checks:
                - missing_count(${entity}_id) = 0: 
                    attributes:
                      category: Accuracy

                - duplicate_percent(${entity}_id) < 0.10:
                    attributes:
                      category: Validity

                - duplicate_count(${entity}_id) = 0:
                    attributes:
                      category: Uniqueness
                      description: The ${entity} column must not contain duplicate values.

                - missing_count(${entity}_id) = 0:
                    attributes:
                      category: Completeness
                      description: The ${entity} column must not contain missing values.

                - invalid_count(item_name) <= 0:
                    valid regex: \b(?:DeviceDriverLoaded|DeviceDriverInstall)\b
                    attributes:
                      category: Validity

                - freshness(created_at)  < 730d:
                    attributes:
                      category: Freshness
                - schema:
                    name: Confirm that required columns are present
                    warn:
                      when required column missing: [${entity}_id]
                    fail:
                      when required column missing:
                        - ${entity}_id
                    attributes:
                      category: Schema 

                -  amount_limit = 1:
                    amount_limit query: |
                      SELECT
                        CASE
                          WHEN cast(amount AS integer)  <= 70 then 1
                          ELSE 0
                        END
                        FROM
                          ${entity}
                    attributes:
                      category: Accuracy
              profile:
                columns:
                  - "*"



